version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/rackup"
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/rackup-server"
    schedule:
      interval: "daily"
