name: license-check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - "rackup/pubspec.yaml"
      - ".github/workflows/license-check.yml"
  push:
    branches:
      - main
    paths:
      - "rackup/pubspec.yaml"
      - ".github/workflows/license-check.yml"

jobs:
  license_check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/license_check.yml@v1
    with:
      allowed: "MIT,BSD-3-Clause,BSD-2-Clause,Apache-2.0"
      working_directory: rackup
